<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120712192604 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE brain_domain_model_action_contexts_join (brain_action VARCHAR(40) NOT NULL, brain_context VARCHAR(40) NOT NULL, INDEX IDX_D47D933731E5819D (brain_action), INDEX IDX_D47D93377294B1E2 (brain_context), PRIMARY KEY(brain_action, brain_context)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE brain_domain_model_action_contexts_join ADD CONSTRAINT FK_D47D933731E5819D FOREIGN KEY (brain_action) REFERENCES brain_domain_model_action (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE brain_domain_model_action_contexts_join ADD CONSTRAINT FK_D47D93377294B1E2 FOREIGN KEY (brain_context) REFERENCES brain_domain_model_context (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE brain_domain_model_action DROP contexts");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE brain_domain_model_action_contexts_join");
		$this->addSql("ALTER TABLE brain_domain_model_action ADD contexts LONGTEXT NOT NULL COMMENT '(DC2Type:array)'");
	}
}

?>