<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120730015130 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE brain_domain_model_action_comments_join (brain_action VARCHAR(40) NOT NULL, brain_comment VARCHAR(40) NOT NULL, INDEX IDX_2CF067B831E5819D (brain_action), INDEX IDX_2CF067B84BD66F0 (brain_comment), PRIMARY KEY(brain_action, brain_comment)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE brain_domain_model_action_comments_join ADD CONSTRAINT FK_2CF067B831E5819D FOREIGN KEY (brain_action) REFERENCES brain_domain_model_action (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE brain_domain_model_action_comments_join ADD CONSTRAINT FK_2CF067B84BD66F0 FOREIGN KEY (brain_comment) REFERENCES brain_domain_model_comment (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE brain_domain_model_comment ADD action VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE brain_domain_model_comment ADD CONSTRAINT FK_E5C0662747CC8C92 FOREIGN KEY (action) REFERENCES brain_domain_model_action (flow3_persistence_identifier)");
		$this->addSql("CREATE INDEX IDX_E5C0662747CC8C92 ON brain_domain_model_comment (action)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE brain_domain_model_action_comments_join");
		$this->addSql("ALTER TABLE brain_domain_model_comment DROP FOREIGN KEY FK_E5C0662747CC8C92");
		$this->addSql("DROP INDEX IDX_E5C0662747CC8C92 ON brain_domain_model_comment");
		$this->addSql("ALTER TABLE brain_domain_model_comment DROP action");
	}
}

?>