<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120712121049 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE brain_domain_model_information (flow3_persistence_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, body VARCHAR(255) NOT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE brain_domain_model_context (flow3_persistence_identifier VARCHAR(40) NOT NULL, tag VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE brain_domain_model_action (flow3_persistence_identifier VARCHAR(40) NOT NULL, owner VARCHAR(40) DEFAULT NULL, assignee VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, contexts LONGTEXT NOT NULL COMMENT '(DC2Type:array)', creationdate DATETIME NOT NULL, INDEX IDX_427D4ED6CF60E67C (owner), INDEX IDX_427D4ED67C9DFC0C (assignee), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE brain_domain_model_comment (flow3_persistence_identifier VARCHAR(40) NOT NULL, owner VARCHAR(40) DEFAULT NULL, body VARCHAR(255) NOT NULL, INDEX IDX_E5C06627CF60E67C (owner), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE brain_domain_model_user (flow3_persistence_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE brain_domain_model_action ADD CONSTRAINT FK_427D4ED6CF60E67C FOREIGN KEY (owner) REFERENCES brain_domain_model_user (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE brain_domain_model_action ADD CONSTRAINT FK_427D4ED67C9DFC0C FOREIGN KEY (assignee) REFERENCES brain_domain_model_user (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE brain_domain_model_comment ADD CONSTRAINT FK_E5C06627CF60E67C FOREIGN KEY (owner) REFERENCES brain_domain_model_user (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE brain_domain_model_user ADD CONSTRAINT FK_132D357221E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES typo3_party_domain_model_abstractparty (flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE typo3_flow3_security_account CHANGE credentialssource credentialssource VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE typo3_party_domain_model_electronicaddress CHANGE usagetype usagetype VARCHAR(20) DEFAULT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE brain_domain_model_action DROP FOREIGN KEY FK_427D4ED6CF60E67C");
		$this->addSql("ALTER TABLE brain_domain_model_action DROP FOREIGN KEY FK_427D4ED67C9DFC0C");
		$this->addSql("ALTER TABLE brain_domain_model_comment DROP FOREIGN KEY FK_E5C06627CF60E67C");
		$this->addSql("DROP TABLE brain_domain_model_information");
		$this->addSql("DROP TABLE brain_domain_model_context");
		$this->addSql("DROP TABLE brain_domain_model_action");
		$this->addSql("DROP TABLE brain_domain_model_comment");
		$this->addSql("DROP TABLE brain_domain_model_user");
		$this->addSql("ALTER TABLE typo3_flow3_security_account CHANGE credentialssource credentialssource VARCHAR(255) NOT NULL");
		$this->addSql("CREATE UNIQUE INDEX flow3_identity_typo3_party_domain_model_electronicaddress ON typo3_party_domain_model_electronicaddress (identifier, type, usagetype)");
	}
}

?>