TYPO3:
  FLOW3:
    security:
      enable: TRUE
      authentication:
        providers:
          BrainProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: brain/login

  Form:
    presets:
      contentManagement:
        formElementTypes:
          'Brain:VariantSelector':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:SelectionMixin']

Foo:
  ContentManagement:
    Annotations:
      Brain\Domain\Model\Information:
        Properties:
          variant:
            OptionsProvider:
              name: Array
              options:
                name,contexts,content: Simple
                name,contexts,items: Group
                name,contexts,host,username,password: SSH
                name,contexts,host,username,password: FTP
                name,contexts,url,username,password: Web Login
                name,contexts,host,database,username,password: Database
                name,contexts,yaml: YAML
                name,contexts,tabular: Table

      Brain\Domain\Model\User:
        active: true
        Properties: 
          name: 
            Inline: Foo.ContentManagement:InlineSeamless
          actions: 
            Ignore: true
          electronicAddresses:
            Inline: Foo.ContentManagement:InlineTabular
            Ignore: true
          primaryElectronicAddress:
            Inline: Foo.ContentManagement:InlineSeamless
          accounts:
            Inline: Foo.ContentManagement:InlineSeamless

      TYPO3\Party\Domain\Model\PersonName:
        Properties:
          title:
            Ignore: true
          otherName:
            Ignore: true
          middleName:
            Ignore: true
          fullName:
            Ignore: true
          alias:
            Ignore: true

      TYPO3\FLOW3\Security\Account:
        Properties:
          accountIdentifier:
            Title: true
          credentialsSource:
            Ignore: true
          credentialsSource:
            Label: Passwort
            #Ignore: true
            Element: TYPO3.Form:SingleLineText
          roles:
            Ignore: true
          creationDate:
            Ignore: true
          party:
            Ignore: true
          expirationDate:
            Ignore: true
          authenticationProviderName:
            Ignore: true

      TYPO3\Party\Domain\Model\ElectronicAddress:
        Properties:
          type:
            Element: TYPO3.Form:SingleSelectDropdown
            OptionsProvider: 
              Name: ConstOptionsProvider
              RegEx: TYPE_.+
          usage:
            Element: TYPO3.Form:SingleSelectDropdown
            OptionsProvider: 
              Name: ConstOptionsProvider
              RegEx: USAGE_.+